
import MainWrapper from "@/wrapper/MainWrapper";
import "./globals.css";
import BlockMouceWheel from "@/utils/BlockMouseWheel";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <MainWrapper>
          {children}
          <Toaster />
          <BlockMouceWheel />
        </MainWrapper>
      </body>
    </html>
  );
}
